version: '3.5'
services:

  php:
    network_mode: bridge
    container_name: php
    image: jguyomard/laravel-php:7.3
    volumes:
      - ./src/:/var/www/
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_PASSWORD=homestead"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    links:
      - mysql
      - redis

  nginx:
    network_mode: bridge
    container_name: nginx
    image: jguyomard/laravel-nginx:1.13
    links:
      - php
    ports:
      - 8081:80

  mysql:
    network_mode: bridge
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=homestead"
    ports:
        - "3306:3306"

  redis:
    container_name: redis
    network_mode: bridge
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
        - "6379:6379"
